name: biophilia

services:
  biophilia:
    build:
      context: ../../..
      dockerfile: ./env/local/docker/Dockerfile
    environment:
      COMMAND: "app"
    container_name: biophilia
    depends_on:
      redis:
        condition: service_healthy
      storage:
        condition: service_healthy
      database:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    env_file:
      - ../../../.env
    ports:
      - "8080:8080"
    volumes:
      - ../../../:/project
      - ../../files/:/files
  migrator:
    build:
      context: ../../..
      dockerfile: ./env/local/docker/Dockerfile
    container_name: migrator
    environment:
      COMMAND: "migrator"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ../../../.env
    volumes:
      - ../../../:/project
  storage:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    container_name: storage
    env_file:
      - ../../../.env
    environment:
      MINIO_ROOT_USER: ${STORAGE_USER}
      MINIO_ROOT_PASSWORD: ${STORAGE_PASSWORD}
      MINIO_USE_SSL: ${STORAGE_USE_SSL}
    volumes:
      - minio-storage:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    healthcheck:
      test: [ "CMD", "curl", "--silent", "--fail", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 10s
      retries: 5
  database:
    image: postgres:15
    container_name: database
    env_file:
      - ../../../.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-catalog:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: redis
    env_file:
      - ../../../.env
    command: --port 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres-data-catalog:
  minio-storage:
