// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/biomolecules": {
            "get": {
                "description": "Get biomolecules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biomolecules"
                ],
                "summary": "Get biomolecules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.Biomolecule"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new biomolecule in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biomolecules"
                ],
                "summary": "Create a new biomolecule",
                "parameters": [
                    {
                        "description": "Biomolecule to create",
                        "name": "biomolecule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.AddBiomoleculeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.Biomolecule"
                        }
                    }
                }
            }
        },
        "/biomolecules/{id}": {
            "get": {
                "description": "Get biomolecule by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biomolecules"
                ],
                "summary": "Get biomolecule by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Biomolecule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Biomolecule"
                        }
                    }
                }
            },
            "put": {
                "description": "Update biomolecule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biomolecules"
                ],
                "summary": "Update biomolecule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Biomolecule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Biomolecule to create",
                        "name": "biomolecule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateBiomoleculeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.Biomolecule"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete biomolecule",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "biomolecules"
                ],
                "summary": "Delete biomolecule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Biomolecule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.AddBiomoleculeRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Essential for oxygen presentation"
                },
                "name": {
                    "type": "string",
                    "example": "Hemoglobin"
                },
                "sequence": {
                    "type": "string",
                    "example": "MVHLTPEEKSA"
                },
                "type": {
                    "type": "string",
                    "example": "protein"
                }
            }
        },
        "entities.Biomolecule": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "sequence": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entities.UpdateBiomoleculeRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Essential for oxygen presentation"
                },
                "name": {
                    "type": "string",
                    "example": "Hemoglobin"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Biophilia API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
